apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
      - mountPath: /data
        name: mypd
        readOnly: true
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: podpvc
