apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: false
mountOptions:
  - discard # this might enable UNMAP / TRIM at the block storage layer
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true" # provider-specific
  type: gp2
